on: [push]
jobs:
  build:
    runs-on: host
    steps:
      - run: |
          git config --global http.sslVerify false
          git clone https://git.lovirent.eu/pacman/blog
          cd blog
          git submodule update --init --recursive
          ls -la
          ls -la themes
      - run: |
          cd blog
          nix build '.?submodules=1'
      - run: |
          mkdir public
          cp -r blog/result/* public
      - run: |
          chmod +w -R /var/lib/runner/blog
          rm -rf /var/lib/runner/blog/*
          cp -r public/ /var/lib/runner/blog
